### ISSUE TITLE
Is there any chance that this project becomes more active?

### ISSUE THREAD

**Issue by lazaridiscom** [vmware/concord-bft#426]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see some nice project in a "kind of abandoned" state.

**Describe the solution you'd like**
More activity, at least bringing the concord project to a real 1.0 version, e.g. with nearly everything clean-up and documented.

Please not that it is impossible to contribute this work, as long as the maintainers are not very active (e.g. dealays with PRs etc.). It is something that vmware needs to want.

**Comment by andrewjstone** [comment]
- This project is far from abandoned. You can look at the number of committers growing over time and the rate of commits and comments. 
- VMware continues to hire to work on this project and invest in it, although we are a relatively small team for the amount of work that needs to be done.
- Many developers have contributed patches within 1 week of starting work. It is far from impossible to contribute to.
- The maintainers work very hard to monitor and manage PRs and communicate daily. We've already merged 2 PRs from you.
- We also very much want to make this a 1.0 project.
- This project is inherently extremely complex, as it's an advanced byzantine fault tolerant state machine replication system. Reading the paper, and the PBFT paper may give you more insight into what the code is supposed to do: 
- We plan to add more detailed documentation over time. Some docs we have written are not quite ready for open source and need to be cleaned and stripped of proprietary information before being shared.
- We have thorough docs inside the repository for various things. We will add more. Not all of them are linked from the main README. This repository contains code for multiple libraries and tools, some of which are documented in their own markdown files and code comments:
  - https://github.com/vmware/concord-bft/tree/master/tests/apollo 
  - https://github.com/vmware/concord-bft/tree/master/storage
  - https://github.com/vmware/concord-bft/blob/master/storage/include/sparse_merkle/internal_node.h
- Sometimes the immediate priorities of our paying customers do not align with those of our opensource users. Without paying customers this project will not get the full time support it needs, and therefore we focus on the needs of those paying customers.
- All work done for paying customers relating to the BFT code becomes open source and is made freely available. We are improving our processes around documentation and testing and working to make it easier to understand that work and what is driving it to the open source community when possible. This process is far from complete.
- Real projects take time to mature. Please be patient.
- The tone of this issue is not valuable for getting people to want to help you out.

**Comment by lazaridiscom** [comment]
>The tone of this issue is not valuable for getting people to want to help you out.

I didn't ask for help. I see that a brand (VMware) that I like does (very obviously) something wrong, and I tried to a) give a "sense of disapointment" and b) find out why things are wrong.

As for you: pleases try to investigate, instead of becoming defensive. And most importantly, do not close issues in that way (comment-close). Frankly, this is rudeness.

If you want follow-up issues (I see several, mostly in documentation), please reopen this issue.

**Comment by teoparvanov** [comment]
@lazaridiscom, I support @andrewjstone in closing the issue, because it's not directly actionable due to its scope.

I suggest to open smaller, more targeted issues instead.

We appreciate your feedback, but we need to find the right language and tone for our communication going forward.

Please note that our team's culture is highly supportive and collaborative. We would like our open source collaborators to also embrace it.

Thank you,
@teoparvanov

**Comment by lazaridiscom** [comment]
> we appreciate your feedback, but we need to find the right language and tone for our communication going forward.

See, neither you appreciate any of my feedback, nor do you respect my individuality of expression.

Yes, you need to find the right language and tone. it's easy:

=> stop beeing patronizing, this has mostly just the effect to ridicule yourself.

> I support @andrewjstone in closing the issue, because it's not directly actionable due to its scope.

See, how does one respond to this? You don't close issues like this (comment-close), understand that this is rudeness.

"not actionable due to its scope"

What else will I hear here? You leave the issue open, until every actionable content was either solved, or moved to other issues.

> I suggest to open smaller, more targeted issues instead.

Really? Like "breaking large issues does to manageable sub-issues"? Fascinating concept, why do you feel the need to communicate this?

This is obvious, what is not obvious to you (and your team here) is that you keep the issues OPEN, until sub-issues are filed.

> Please note that our team's culture is highly supportive and collaborative. We would like our open source contributors to also embrace it.

Your self-assessment "highly supportive and collaborative" is a bit invalid.

The proof is right within this issue, where you behave hostile and even discriminating against my person.

In this context, may I ask where I can formally complain?

And who is the project-lead here?

**Comment by teoparvanov** [comment]
@lazaridiscom, I don't believe my message warrants such a response. If you want to help us, please do so in a less aggressive way. 

We have already merged 2 of your PR-s in a matter of days, which we thank you for. Would you like to go deeper in understanding and improving Concord-BFT? If so, we can provide you reading materials and additional pointers.

**Comment by lazaridiscom** [comment]
@teoparvanov , this is a close issue. I'm leaving it.
